### ISSUE TITLE
Issue with Streamlit settings 

### ISSUE THREAD

**Issue by kastnerp** [sushantgadgil/VroomVroom#2]
I just checked all the links when posting on LinkedIn and it seems something might be broken.
Maybe the app is set to private mode? It worked two days ago when I looked at it for grading.

```
Unsupported browser
Streamlit uses third-party cookies for authentication, but your browser does not support them. We are busy working on support for all browsers but, in the meantime, you can either [enable third-party cookies ](https://streamlit.notion.site/Enable-Third-Party-Cookies-in-Your-Browser-f9b346d904b2408e854dd37c50d6f9f7)or use a different browser, such as [Chrome](https://www.google.com/chrome).
```

Best,

Patrick

**Comment by sushantgadgil** [comment]
Hmm, very strange. It seems to be working for me as of 6:55 PM PT (5/24) using Google Chrome Version 101.0.4951.64 and Safari Version 15.4 (17613.1.17.1.13). What browser are you using?

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/98911787/170162907-cd265c32-8bc7-423a-b4be-125602772e1a.png">

**Comment by kastnerp** [comment]
On Chrome too, glad it works on your end. Must be my setup then!
